"""initial schema

Revision ID: 715d9926ec42
Revises: 
Create Date: 2026-05-05 23:24:46.181777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715d9926ec42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_polled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickers_symbol'), ['symbol'], unique=True)

    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('feed_source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['feed_sources.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index('ix_article_ticker_pub', ['ticker_id', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_feed_source_id'), ['feed_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_ticker_id'), ['ticker_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('dividends', sa.Float(), nullable=True),
    sa.Column('stock_splits', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'timestamp', name='uq_ticker_timestamp')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_ticker_id'), ['ticker_id'], unique=False)
        batch_op.create_index('ix_price_ticker_ts', ['ticker_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_ticker_ts')
        batch_op.drop_index(batch_op.f('ix_price_history_ticker_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_ticker_id'))
        batch_op.drop_index(batch_op.f('ix_news_articles_feed_source_id'))
        batch_op.drop_index('ix_article_ticker_pub')

    op.drop_table('news_articles')
    with op.batch_alter_table('tickers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickers_symbol'))

    op.drop_table('tickers')
    op.drop_table('feed_sources')
    # ### end Alembic commands ###
